# Flutter Web App Rebuild Script with Flexible Layout Fix
# This script updates the Flutter build while preserving our fixes

Write-Host "WARNING: This will overwrite existing Flutter changes!"
Write-Host "Make sure your Dart code changes are saved first."
Write-Host ""
Write-Host "Note: The actual Flutter rebuild requires:"
Write-Host "1. Flutter SDK in PATH"  
Write-Host "2. Running: flutter build web --web-renderer html"
Write-Host ""
Write-Host "Since Flutter SDK is not available in this terminal,"
Write-Host "the layout changes in tip_calculator_screen.dart need to be"
Write-Host "compiled by running Flutter build manually."
Write-Host ""
Write-Host "Current changes made to tip_calculator_screen.dart:"
Write-Host "- Changed MainAxisSize.min to MainAxisSize.max"
Write-Host "- Added Expanded widget around InputSection"  
Write-Host "- Removed Center and Container constraints"
Write-Host "- Added SingleChildScrollView to wide screen layout"
Write-Host ""
Write-Host "These changes should make the layout flexible and scrollable."